### ISSUE TITLE
Not sure where to install/put files

### ISSUE THREAD

**Issue by davidwieler** [d-karl/Rocket-League-Chroma-Control#1]
Can you include a brief step list of where to put the files / install this app.

I really want to help test this, but I have no idea where to put anything.

**Comment by d-karl** [comment]
Ok this is weird, it should be pretty straightforward. Download the latest release from here: https://github.com/d-karl/Rocket-League-Chroma-Control/releases. Extract the archive wherever you like, just make sure you extract **everything**. Go inside recently unzipped folder, run RocketLeagueChromaControl.exe.

**Comment by davidwieler** [comment]
You're right, very weird. I downloaded the source code like a noob ...
