### ISSUE TITLE
Not reacting to scored goals, and not reacting to match countdown properly

### ISSUE THREAD

**Issue by bwarren97** [d-karl/Rocket-League-Chroma-Control#3]
It seems it's been quite a while since the app has been updated, Chroma is not reacting at all to scored goals. Also only reacts occasionally to a "3-2-1" countdown

**Comment by d-karl** [comment]
Hey, thank you for your interest in my little application. As of right now this is a known problem and I can't promise that it will ever be fixed. Detailed explanation follows.

The way in which RLCC was detecting events happening inside Rocket League was through the events logged by the Unreal engine (through the console window that is opened in the background when you start Rocket League). As they thought their product was more mature, Psyonix has lowered the log-level. This means that RLCC is no longer able to detect events using this method. This change has happened a long time ago, might have been more than a year even.

There are other applications around Rocket League (such as Bakkes' mod) that can detect and modify the game through hooking into it's memory. I am open to someone using the code in this repository and merging it with some other event-detection mechanism. I might look into this myself, but I can't promise anything, as its a very complicated process and potentially hugely problematic seeing as this is an online game first. If anyone has some code dealing with event-detection in Rocket League I would be glad if you could point me into its direction.
