### ISSUE TITLE
Project Aurora

### ISSUE THREAD

**Issue by diogotr7** [d-karl/Rocket-League-Chroma-Control#5]
Me and a couple other users of [Project Aurora](https://github.com/antonpup/Aurora) have been trying to find pointers to rocket league values with some success lately. We have boost, goals for each team, and current team the player is in. 
We would love to have rocket league support on rgb keyboards more consistently so we'd love some help if you're interested :) . You can find us in our discord [here](https://discordapp.com/invite/YAuBmg9)

**Comment by d-karl** [comment]
This is great, I'll make sure to say hi, expect me next weekend at the latest.

**Comment by diogotr7** [comment]
Hey, I decided to finally find a non-hacky way to find the values and wrote this plugin for bakkesmod if you're interested: https://github.com/diogotr7/AuroraGSI-RocketLeague

I've also added support for this integration to Project Aurora.

**Comment by d-karl** [comment]
Thank you very much for letting me know this is a thing. Now I am considering porting the effects into a BakkesMod plugin. That could be neat.
